### ISSUE TITLE
Supporting the new version of IDE (Android Studio Iguana | 2023.2.1 Patch 1)

### ISSUE THREAD

**Issue by ra-develop** [thelumiereguy/ComposeHelperPlugin#4]
Plugin 'Compose Helper' (version '2.0.4') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is AI-232.10300.40

**Comment by thelumiereguy** [comment]
Hey @ra-develop. Sorry for the delay. 
Coincidentally, I just released a new version yesterday - https://github.com/thelumiereguy/ComposeHelperPlugin/pull/3

It should be published tomorrow or the day after.  👍

**Comment by thelumiereguy** [comment]
Released!

**Comment by ra-develop** [comment]
Thank you very much! Well done!
